==> Workflow engine logs
2024-09-24 12:06:39,084 | root | MainThread | INFO | Publishing step:0, cmd: python "code/exception.py" --inputfile "data/names.txt" --outputfile "results/greetings.txt" --sleeptime 1.0, total steps 1 to MQ
2024-09-24 12:07:10,879 | root | kubernetes_job_monitor | WARNING | Job pod reana-run-job-41117903-e496-42ad-9bd2-247d1c64a5ae-xxprr was terminated, reason: Error, message: None
2024-09-24 12:07:15,275 | root | MainThread | INFO | Workflow d0834d49-5d2e-408f-bcd1-ebee9b05f25e finished. Files available at /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/d0834d49-5d2e-408f-bcd1-ebee9b05f25e.



==> Job logs
==> Step: hello1
==> Workflow ID: d0834d49-5d2e-408f-bcd1-ebee9b05f25e
==> Compute backend: Kubernetes
==> Job ID: reana-run-job-41117903-e496-42ad-9bd2-247d1c64a5ae
==> Docker image: docker.io/library/python:3.8-slim
==> Command: python "code/exception.py" --inputfile "data/names.txt" --outputfile "results/greetings.txt" --sleeptime 1.0
==> Status: failed
==> Started: 2024-09-24T12:06:39
==> Finished: 2024-09-24T12:07:10
==> Step hello1 emitted no logs.
{
  "job_id": "33047e67-f19c-4117-bcb4-a387056db8df",
  "job_name": "hello1",
  "logs": "2024-09-24T12:06:39 INFO     Parameters: inputfile=data/names.txt outputfile=results/greetings.txt sleeptime=1.0\n0 Hello Jane Doe!\n1 Hello Joe Bloggs!\n2 Hello Jane Doe!\n3 Hello Joe Bloggs!\n4 Hello Jane Doe!\n5 Hello Joe Bloggs!\n6 Hello Jane Doe!\n7 Hello Joe Bloggs!\n8 Hello Jane Doe!\n9 Hello Joe Bloggs!\n10 Hello Jane Doe!\n11 Hello Joe Bloggs!\n12 Hello Jane Doe!\n13 Hello Joe Bloggs!\n14 Hello Jane Doe!\n15 Hello Joe Bloggs!\n16 Hello Jane Doe!\n17 Hello Joe Bloggs!\n18 Hello Jane Doe!\n19 Hello Joe Bloggs!\n20 Hello Jane Doe!\n21 Hello Joe Bloggs!\n22 Hello Jane Doe!\n23 Hello Joe Bloggs!\n24 Hello Jane Doe!\n25 Hello Joe Bloggs!\n26 Hello Jane Doe!\n27 Hello Joe Bloggs!\n28 Hello Jane Doe!\n29 Hello Joe Bloggs!\nTraceback (most recent call last):\n  File \"code/exception.py\", line 100, in <module>\n    hello(parsed_args.inputfile, parsed_args.outputfile, parsed_args.sleeptime)\n  File \"code/exception.py\", line 62, in hello\n    raise Exception(\"This is a test exception\")\nException: This is a test exception\n",
  "status": "failed",
  "user": "00000000-0000-0000-0000-000000000000"
}
